// <auto-generated />
using System;
using HamaraBasketRuleEngine.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HamaraBasketRuleEngine.Repository.Migrations
{
    [DbContext(typeof(HamaraBasketRuleEngineContext))]
    [Migration("20210613154815_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HamaraBasketRuleEngine.Domain.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quality")
                        .HasColumnType("int");

                    b.Property<int?>("SellBy")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("HamaraBasketRuleEngine.Domain.RuleByItem", b =>
                {
                    b.Property<int>("ReleByItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("MaxQualityValue")
                        .HasColumnType("int");

                    b.Property<int>("MinQualityValue")
                        .HasColumnType("int");

                    b.Property<int>("QualityChangesAfterSellByDay")
                        .HasColumnType("int");

                    b.Property<int>("QualityChangesOverApproachingSellByDay")
                        .HasColumnType("int");

                    b.HasKey("ReleByItemId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("RuleByItems");
                });

            modelBuilder.Entity("HamaraBasketRuleEngine.Domain.RuleByNumberOfDaysLeft", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DaysLeftToSellByDate")
                        .HasColumnType("int");

                    b.Property<int>("QualityChangesByDaysLeft")
                        .HasColumnType("int");

                    b.Property<int>("RuleByItemId")
                        .HasColumnType("int");

                    b.HasKey("RuleId");

                    b.HasIndex("RuleByItemId");

                    b.ToTable("RuleByNumberOfDaysLefts");
                });

            modelBuilder.Entity("HamaraBasketRuleEngine.Domain.RuleByItem", b =>
                {
                    b.HasOne("HamaraBasketRuleEngine.Domain.Item", "Item")
                        .WithOne("RuleByItem")
                        .HasForeignKey("HamaraBasketRuleEngine.Domain.RuleByItem", "ItemId")
                        .HasConstraintName("FK_RuleByItem_ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("HamaraBasketRuleEngine.Domain.RuleByNumberOfDaysLeft", b =>
                {
                    b.HasOne("HamaraBasketRuleEngine.Domain.RuleByItem", "RuleByItem")
                        .WithMany("RuleByNumberOfDaysLeft")
                        .HasForeignKey("RuleByItemId")
                        .HasConstraintName("FK_RuleByNumberOfDaysLeft_RuleByItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleByItem");
                });

            modelBuilder.Entity("HamaraBasketRuleEngine.Domain.Item", b =>
                {
                    b.Navigation("RuleByItem");
                });

            modelBuilder.Entity("HamaraBasketRuleEngine.Domain.RuleByItem", b =>
                {
                    b.Navigation("RuleByNumberOfDaysLeft");
                });
#pragma warning restore 612, 618
        }
    }
}
